### ISSUE TITLE
Morning Session : Peer-to-Peer Review

### ISSUE THREAD

**Issue by elarhadu** [MohamedHNoor/To-Do-list#3]
Hi @MohamedHNoor ,

Great work on your project.  But I'd suggest you'd remove the [eslint from this line](https://github.com/MohamedHNoor/To-Do-list/blob/f6496dd8722f6a064c9c6f8b6e47404f030be54f/src/functionality.js#L5) and try to fix the linter error as these checks are meant to help you have a clean code base.

**Comment by MohamedHNoor** [comment]
ok
